import { Component } from '@angular/core';

export interface Item {
  link: string;
  name: string;
  description: string;
  rating: number;
  bonus: string[];
  numLike: number;
  exist: boolean;
}

export interface Category {
  name: string;
  iteems: Item[];
  show: boolean;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'MY-STORE';
  cnt = 0;
  public laptop: Item[] = [
    {link: 'https://www.amazon.com/Wireless-Multi-Device-Mechanical-Rechargeable-Switch-White/dp/B0731CJ4ZJ/ref=sr_1_12?crid=27Q8Q6S61XOF5&dchild=1&keywords=mechanical+keyboard&qid=1614127499&sprefix=mec%2Caps%2C397&sr=8-12', name: '60% Mechanical Gaming Keyboard', description: '60% Compact Minimalism Layout: Ultra-compact layout with 61 keys makes you a neat desktop with your organized gears on, even folks have nothing to do with Minimalist will dive into its tiny practical design.', rating: 4.6, bonus: ['https://images-na.ssl-images-amazon.com/images/I/61EMrO4vAEL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/713Y%2BMAxwrL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81DWY18NzrL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Samsung-23-5-Inch-LED-Lit-Monitor-LC24F396FHNXZA/dp/B079K3MXWF/ref=sr_1_7?crid=1IDHK12MUK1F5&dchild=1&keywords=monitor&qid=1614127944&sprefix=monitor%2Caps%2C363&sr=8-7', name: 'LED-Lit FreeSync Monitor', description: 'SAMSUNG LC24F396FHNXZA 23.5\' FHD Curved LED-Lit FreeSync Monitor', rating: 4.1, bonus: ['https://images-na.ssl-images-amazon.com/images/I/91RLPTjVeaL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/91ubktnbNVL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/919UaTfV0jL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/iBUYPOWER-Computer-Desktop-Trace-9310/dp/B08FPL6S4Y/ref=sr_1_5?dchild=1&keywords=computer&qid=1614488000&sr=8-5', name: 'iBUYPOWER Gaming PC Computer Desktop Trace 4 9310', description: ' 8GB DDR4 RAM, 240GB SSD, Wi-Fi Ready, Windows 10 Home.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71CyfrhCZ1L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81nxSCmXGrL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71kvx9ckknL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/KLIM-Ultimate-Laptop-Cooling-backlighting/dp/B07NNQXTQT/ref=sr_1_8?dchild=1&keywords=%3Dcooler+for+laptop&qid=1614488235&sr=8-8', name: 'RGB Laptop Cooling Pad with LED Rim, Gaming Laptop Cooler', description: 'The KLIM Ultimate is not another generic one-led cooling pad, it combines style and efficient cooling.', rating: 4.6, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71UdbBD3c0L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71jRu1JpS-L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61PtaRDqFkL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/AutoFocus-Microphone-NexiGo-Streaming-Compatible/dp/B08931JJLV/ref=sr_1_2_sspa?dchild=1&keywords=camera+for+PC&qid=1614488401&sr=8-2-spons&psc=1&smid=A1HNC035CZ2MR5&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzTFJJU1VTSlFHR01FJmVuY3J5cHRlZElkPUEwNjgyMjcxM0pETklFMzZKSlM5SSZlbmNyeXB0ZWRBZElkPUEwNTQzMzcxM0pJME9NTlg1UElDTCZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: '2021 AutoFocus 1080p Webcam with Stereo Microphone and Privacy Cover', description: 'The NexiGo PC External Webcam with a 2-megapixel CMOS features up to a 1080p resolution at 30fps.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/61BGZKR0OBL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/718hRcShK3L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/413OM8T00iL._AC_.jpg'], numLike: 0, exist: true},
  ];
  public marvel: Item[] = [
    {link: 'https://www.amazon.com/dp/B0858C7PQ5/ref=redir_mobile_desktop?_encoding=UTF8&aaxitk=J7L.QmSzpngPO4e9vPtYVg&hsa_cr_id=1232002990201&pd_rd_plhdr=t&pd_rd_r=fc680713-1606-4e80-8f9e-2522e40c6f3e&pd_rd_w=dO5CN&pd_rd_wg=M1Ujy&ref_=sbx_be_s_sparkle_mcd_asin_0_title', name: 'LEGO Marvel Avengers Helicarrier', description: 'Includes Iron Man, Captain Marvel, Thor, Black Widow, War Machine, Nick Fury and A.I.M.', rating: 4.9, bonus: ['https://images-na.ssl-images-amazon.com/images/I/91hZ3A31pKL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71rDopFmo0L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81YeBj8sxZL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Ergonomic-Wireless-Portable-Computer-Receiver/dp/B08CSH4W8L/ref=sr_1_1_sspa?dchild=1&keywords=iron+man&qid=1614128832&sr=8-1-spons&psc=1&smid=A3NCJ7M1W7600A&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEySTY3QVhNWTBIRVZXJmVuY3J5cHRlZElkPUEwNjYwNTU1OFFZS0ZITURMRlY3JmVuY3J5cHRlZEFkSWQ9QTA1NTI2ODMxNExCOUxCRDE1NE5YJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==', name: 'Ergonomic Wireless Mouse, Cool Iron Man Mouse 2.4G', description: '800 / 1200 / 1600 DPI Resolution Optical Tracking Technology provides more sensitivity than standard optical mice for smooth and precise tracking on a wide range of surfaces.', rating: 4.4, bonus: ['https://images-na.ssl-images-amazon.com/images/I/51UDD7nRpUL._AC_SL1000_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61HPyFtyzsL._AC_SL1337_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Hands-Gloves-Cosplay-Costume-Accessories/dp/B07F8PWBXK/ref=sr_1_1_sspa?dchild=1&keywords=hulk+hands&pd_rd_r=7d1ddb13-bd8d-4c3f-8765-395588ac49a8&pd_rd_w=16MKd&pd_rd_wg=GrPxg&pf_rd_p=727d959b-87dc-4522-a597-27f83d5cb378&pf_rd_r=N3A2MZJ15V8SBXCYH88B&qid=1614480869&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFENzZJWTYxSU9GSEwmZW5jcnlwdGVkSWQ9QTA1MTA5ODUyMFVNMjk0WUUwVU9EJmVuY3J5cHRlZEFkSWQ9QTA5NzI5NjMyOTQ0RUZCMlZFQTRJJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==', name: 'Hulk hands', description: 'A handle inside the gloves for support and control movement.', rating: 4.7, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71WyAayTfIL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71JKrlbhREL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71t6OC-NePL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Funko-Pop-Deluxe-Marvel-Exclusive/dp/B08B74QR1P/ref=sr_1_31?dchild=1&keywords=avengers&qid=1614481145&sr=8-31', name: 'Captain America, Amazon Exclusive', description: 'Start or complete your Avengers Assemble series today by securing the final figure, Captain America! Exclusively available here!', rating: 4.9, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71t-lkpbaKL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71BO0MR4BHL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61WuI72I%2BuL._AC_SL1000_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Funko-Pop-Deluxe-Marvel-Exclusive/dp/B0892SWZCV/ref=pd_sbs_2?pd_rd_w=e5UqU&pf_rd_p=5e0f7f8d-f321-4a3e-bdac-3142fcd848d7&pf_rd_r=69F5TJ29WCP5CFYR1W8R&pd_rd_r=ae9a6d4e-a3d1-46a3-b5e2-916c562f8abe&pd_rd_wg=XCQJk&pd_rd_i=B0892SWZCV&psc=1', name: 'Avengers Assemble Series - Thor', description: 'Start your Avengers Assemble series today by securing Thor!', rating: 4.9, bonus: ['https://images-na.ssl-images-amazon.com/images/I/61kvChUVxLL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/616a28hbd5L._AC_SL1000_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/51LC%2Bxid%2B9L._AC_SL1027_.jpg'], numLike: 0, exist: true},
  ];
  public music: Item[] = [
    {link: 'https://www.amazon.com/Alesis-Melody-MKII-Built-Headphones/dp/B07987K4F5/ref=sr_1_5?dchild=1&keywords=piano&qid=1614128604&sr=8-5', name: 'Alesis Melody 61 MKII ', description: '61 responsive piano style keys with built in speakers perfect for practicing and performing to your friends and family', rating: 4.6, bonus: ['https://images-na.ssl-images-amazon.com/images/I/817%2BUBFpyNL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/91UXUnOcqJL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81LU48Ve7aL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Fender-Squier-Dreadnought-Acoustic-Guitar/dp/B07MLDZCPP/ref=sr_1_9?dchild=1&keywords=guitar&qid=1614487266&sr=8-9', name: 'Fender Squier Dreadnought Acoustic Guitar', description: 'Scalloped "X"-bracing, mahogany neck and a durable dark-stained maple fingerboard', rating: 4.7, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71a47TiyS6L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61OdOW-BgJL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71otxSSkXwL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/LAGRIMA-Electric-Keyboard-Instruction-Headphone/dp/B07D775C3P/ref=sr_1_13?dchild=1&keywords=piano&qid=1614487434&sr=8-13', name: 'LAGRIMA Digital Piano with Bench', description: '80 demo songs/480 tones/128 standard GM tones/200 present rhythms.', rating: 4.4, bonus: ['https://images-na.ssl-images-amazon.com/images/I/61GDOzMI1GL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71g6OsLOhFL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61Av-pff61L._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Aklot-Mahogany-String-Tuning-Wrench/dp/B082NRLJH1/ref=sr_1_2?dchild=1&keywords=harp&qid=1614487575&sr=8-2', name: 'Aklot Lyre Harp Mahogany', description: '15 String Nylon with Carry Bag Tuning Wrench String Strap', rating: 4.4, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71y4kVT1HVL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61wa41qCnPL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61lTQTRQqIL._AC_SL1200_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Cecilio-CCO-100-Student-Bridge-Strings/dp/B007NG3V64/ref=sr_1_1_sspa?dchild=1&keywords=music+instruments&qid=1614487707&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExT1lFQjZFSUJRVzhUJmVuY3J5cHRlZElkPUEwNDYwMTM3MVcwMlhVM1lVRUYwSCZlbmNyeXB0ZWRBZElkPUEwNTQ4MDg3M0c2NDJXWjYyR1A0WSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: 'Mendini By Cecilio Cello', description: 'Musical Instrument For Kids & Adults - Cellos Kit w/Bow, Stand.', rating: 4.2, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71mZQ0ZBLlL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71ZnnCjQaVL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71xt2lbsrQL._AC_SL1500_.jpg'], numLike: 0, exist: true},
  ];
  public need: Item[] = [
    {link: 'https://www.amazon.com/Amolife-Upholstered-Foundation-Adjustable-Headboard/dp/B08R3D25MW/ref=sr_1_1_sspa?dchild=1&keywords=bed&qid=1614488747&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzMFMwNk1BN1FXWUJaJmVuY3J5cHRlZElkPUEwMjYxNDI5M0NaWjFKNzBBWFRDNyZlbmNyeXB0ZWRBZElkPUEwNjMwNTYwM0tEVjRLRFhRSkFWNiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: 'Amolife Modern Upholstered Bed Frame with Extra Speaker Space', description: '2 Packages: Your order includes two packages, including headboard, footrest, frame, legs and wooden slats.', rating: 4.7, bonus: ['https://images-na.ssl-images-amazon.com/images/I/711CAOkwgJL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/714IO6zArEL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61WHWW%2BqIjL._AC_SL1200_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Hikenture-Camping-Pillow-Removable-Cover/dp/B083YZWZ2L?ref_=ast_sto_dp', name: 'Hikenture Camping Pillow with Removable Cover', description: 'UPGRADE FOR BEST DURABILITY - No more air leaks with our upgraded camping pillow!', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71QbYbIoM6L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71bEqQKNq7L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71guLnuUHgL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Cotton-Sleep-Eye-Mask-Comfortable/dp/B07D3M5TTZ/ref=sr_1_6?crid=FH1LNTO95CQ2&dchild=1&keywords=sleep+mask&qid=1614488983&sprefix=sleep+ma%2Caps%2C362&sr=8-6', name: 'Mavogel Cotton Sleep Eye Mask', description: 'Updated Design Light Blocking Sleep Mask, Soft and Comfortable Night Eye Mask for Men Women.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71dXRhaS6NL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71ddOUAQ5ML._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71xSl4hqryL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Hatch-Restore-Machine-Personal-Routine/dp/B087M94WWW/ref=sr_1_1_sspa?dchild=1&keywords=for+sleep+light&qid=1614489212&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExRUQ5Vjc5NEtLWUJaJmVuY3J5cHRlZElkPUEwNTU5NTg2SDVUUFM5VVBPUkxSJmVuY3J5cHRlZEFkSWQ9QTAwNTc2OTUxUzlXNElKV0NUTUhKJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==', name: 'Hatch Restore - Sound Machine, Smart Light, Personal Sleep Routine', description: 'Sleep better: Personalize a sleep-wake routine to help you fall asleep, stay asleep & wake up refreshed.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/81svGGuAJXL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71q1zbH2%2BbL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/811X4K3OPBL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Howard-Miller-645-584-Audra-Table/dp/B000YDGXUY/ref=sxin_10_ac_d_pm?ac_md=4-2-QWJvdmUgJDUw-ac_d_pm&crid=1D23UH8W8S693&cv_ct_cx=alarm+clock&dchild=1&keywords=alarm+clock&pd_rd_i=B000YDGXUY&pd_rd_r=2cca5ba3-7f42-42d1-8600-b6422f5d6321&pd_rd_w=Ycfak&pd_rd_wg=sZ6ne&pf_rd_p=36deca3f-0240-4c64-a598-47f52c2ef1fb&pf_rd_r=Z8J2J484WH5J45C732P2&psc=1&qid=1614489530&sprefix=alarm+c%2Caps%2C364&sr=1-3-22d05c05-1231-4126-b7c4-3e7a9c0027d0', name: 'Howard Miller Audra', description: 'A brushed and polished brass finish gives this metal carriage alarm clock its enduring style.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71bNBjP7rHL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61sHgLJy%2B%2BL._AC_SL1200_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/31jQAPBNfIL._AC_.jpg'], numLike: 0, exist: true},
  ];
  public led: Item[] = [
    {link: 'https://www.amazon.com/Backlight-Maylit-6-56ft-Accent-Lighting/dp/B074KFP426/ref=sr_1_5?dchild=1&keywords=decor&qid=1614128467&sr=8-5', name: 'Tv Led Backlight', description: 'Functional Applications: led strip lights mainly used for TV decoration, 4*1.64ft led lights for tv light, improve image clarity', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71h1yvgCwAL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81ZB1fKiQ5L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71gEXNAAGHL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/mixigoo-Desk-Lamp-Wireless-Charger/dp/B07VV9MJBY/ref=sr_1_1_sspa?dchild=1&keywords=lamp&qid=1614128116&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExNUZaN1BGN04zUk03JmVuY3J5cHRlZElkPUEwNzk5MTYwMk1NVjJDVFBCTjlSWSZlbmNyeXB0ZWRBZElkPUEwNDk1MjEwMVVGR1pBQU1HS01PVyZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: 'Desk Lamp LED Wireless Charger', description: 'USB Charging Port 5 Lighting Modes 5 Brightness Levels Sensitive Control Auto Timer Eye-Caring Study Work Home Office Lamp for Kids Children (Black)', rating: 4.3, bonus: ['https://images-na.ssl-images-amazon.com/images/I/51s2PUhEmbL._AC_SL1000_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61e3S6gSH%2BL._AC_SL1000_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61QAnZWwUEL._AC_SL1000_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Hyperikon-H-Type-Integrated-Equivalent-Daylight/dp/B078RVCB1Z/ref=sr_1_27_sspa?dchild=1&keywords=lights+led&qid=1614489638&s=home-garden&sr=1-27-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzS0gyOFNLOVg0V1hBJmVuY3J5cHRlZElkPUEwOTM1NzMyQlEwOUZJOE5YQVlLJmVuY3J5cHRlZEFkSWQ9QTA5NTI2NDVQRTVSVjgzN1FQWEgmd2lkZ2V0TmFtZT1zcF9hdGZfbmV4dCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: 'Hyperikon LED Track Head Lighting', description: 'FIT FOR H-TRACK - Our H Type lighting track heads can be installed on all H-Style single circuit track systems.', rating: 4.5, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71CgT862jzL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71qEhXNBl-L._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/713Y3BNX9dL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/dp/B07QJ3XC7J/ref=sspa_dk_detail_2?psc=1&pd_rd_i=B07QJ3XC7J&pd_rd_w=A44cB&pf_rd_p=cbc856ed-1371-4f23-b89d-d3fb30edf66d&pd_rd_wg=usfhM&pf_rd_r=ZMWFT2QQZS0EEQS5XFC2&pd_rd_r=c0e88f78-0ecb-4e26-b84e-ac005a3ba73b&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExVlJLWUxDUjQ3WTZNJmVuY3J5cHRlZElkPUEwNDQyNzUwMzhKUTE5TTBHTFJaNiZlbmNyeXB0ZWRBZElkPUEwNzcxNTQwM0NWSEJES0NMRUIxMSZ3aWRnZXROYW1lPXNwX2RldGFpbF90aGVtYXRpYyZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=', name: '2x4 FT White LED Flat Panel Troffer Light', description: 'HIGH PERFORMANCE - Smoothly dimming compatible with 0-10V dimmers. No flashing, No noise. ', rating: 4.6, bonus: ['https://images-na.ssl-images-amazon.com/images/I/61tvoPrCjrL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61KCC4%2Bx8PL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/710FCE4TJWL._AC_SL1500_.jpg'], numLike: 0, exist: true},
    {link: 'https://www.amazon.com/Ultra-Thin-Recessed-Daylight-Downlight-Certified/dp/B07Q236T4G/ref=sr_1_30?dchild=1&keywords=lights+led&qid=1614489638&s=home-garden&sr=1-30', name: '6 Ultra-Thin Led Recessed Lights', description: 'Only output at 12.5 watt, provide 850lm well-balanced light which equals to an 60W incandescent lamps.', rating: 4.7, bonus: ['https://images-na.ssl-images-amazon.com/images/I/71nhNisn-NL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71HeVXZkJjL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/61CWNBozz-L._AC_SL1500_.jpg'], numLike: 0, exist: true},
  ]
  public categories: Category[] = [
    {name: 'Marvel Studio', iteems: this.marvel, show: false},
    {name: 'For your PC and laptop', iteems: this.laptop, show: false},
    {name: 'Music Instruments', iteems: this.music, show: false},
    {name: 'LED Lights', iteems: this.led, show: false},
    {name: 'For Good Sleep', iteems: this.need, show: false},
    // {name: ''}
  ];
  ChangeIt(name: string): void {
    for (const i of this.categories) {
      if (i.name === name) {
        if (this.cnt === 0 || this.cnt === 1 && i.show === true) {
          if (i.show === true) {
            i.show = false;
            this.cnt = 0;
          } else {
            this.cnt++;
            i.show = true;
          }
        }
      }
    }
  }
}
